### ISSUE TITLE
Unable to create a new receiving address

### ISSUE THREAD

**Issue by extrapockets** [BenWestgate/Bails#86] opened 2023-09-09 13:47 UTC
After initial sync & importing a BAILS-created wallet: Under the Receive tab, I cannot create a new receiving address to send a small test transaction (button is grayed out). I tried filling out all the forms, changing from Bech32, closing the wallet, restarting Core, and restarting Tails, but still no luck. The Window > Receiving addresses window shows no addresses.

**Comment by BenWestgate** [comment] 2023-09-09 13:54
can you press `Ctrl+T` in Bitcoin Core while this BAILS-created wallet is open console and type: `listdescriptors`

If you DO NOT intend to use this wallet, you may paste the output of the command directly.

Otherwise remove the "xpub...." strings to keep your privacy.

There should be 8 descriptors, all marked `"active": true`, half marked `"internal": true` the other half `"internal": false`.

**Comment by extrapockets** [comment] 2023-09-09 13:59
Output was just the wallet name and an empty array after 'descriptors'

**Comment by BenWestgate** [comment] 2023-09-09 14:01
OK, that means the RPC commands to import descriptors failed.

Now I'd like you to type:

`git clone https://github.com/BenWestgate/Bails; */b` in Terminal. This will update Bails and Bitcoin Core to the latest versions (without losing your blockchain sync or wallet!!!). Due to your long sync it's hard for me to know what the code you're running exactly is that experienced this RPC issue.

After you have typed this, click Applications > Office > Bails and select "Wallet" from the menu and you can restore your codex32 seed again.

**Comment by extrapockets** [comment] 2023-09-09 14:25
Unfortunately that did not resolve the issue - still can't generate receive addresses, and the listdescriptors cmd outputs an empty array.

**Comment by extrapockets** [comment] 2023-09-09 14:28
More context: this BAILS-created wallet is from 3 weeks ago, before my sync. I'm going to create a new wallet and see if I can generate an address with that.

**Comment by extrapockets** [comment] 2023-09-09 14:51
> More context: this BAILS-created wallet is from 3 weeks ago, before my sync. I'm going to create a new wallet and see if I can generate an address with that.

The new wallet also cannot create addresses. I made sure to select the new wallet in the console and the receive address tab, as I currently have both wallets open.

**Comment by BenWestgate** [comment] 2023-09-09 15:02
Okay, thanks for your report. I will try to reproduce it now.

**Comment by BenWestgate** [comment] 2023-09-09 15:10
I possibly found the bug:
`export CLI="bitcoin-cli" # rpcport=17600 must be set in bitcoin.conf for Tails.`

I was working on my Bails the other day and noticed either rpcport wasn't set in bitcoin.conf or the bitcoin.conf did not persist correctly.

By the way, while you're here.  Would you like me to make "bails-wallet" this codex32 create and restore utility into a stand alone repro that you can run it on any system that has bitcoin core installed (windows, linux, etc) not just Tails?

**Comment by BenWestgate** [comment] 2023-09-09 15:50
I've recreated the issue.

**Comment by extrapockets** [comment] 2023-09-09 16:02
> I possibly found the bug: `export CLI="bitcoin-cli" # rpcport=17600 must be set in bitcoin.conf for Tails.`
> 
> I was working on my Bails the other day and noticed either rpcport wasn't set in bitcoin.conf or the bitcoin.conf did not persist correctly.
> 
> By the way, while you're here. Would you like me to make "bails-wallet" this codex32 create and restore utility into a stand alone repro that you can run it on any system that has bitcoin core installed (windows, linux, etc) not just Tails?

I think that's a good idea so there is less friction to get users to test the codex32 create & restore utility. Am I right in assuming that a monitor is required to use that utility? I am currently only running core on Ubuntu Server. I can easily set up Bitcoin Core on a laptop to test it with a GUI though.

**Comment by BenWestgate** [comment] 2023-09-09 16:24
I'll make an issue on it. The whole bails-wallet file needs a refactor because its size and evolution has made tracking bugs like this harder. And more eyes on the wallet code means less bugs for Bails users and more people using codex32 with bitcoin core.

You will need a monitor, I don't have plans to write a Terminal User Interface for `bails-wallet` anytime soon.

**Comment by extrapockets** [comment] 2023-09-09 16:27
> I'll make an issue on it. The whole bails-wallet file needs a refactor because its size and evolution has made tracking bugs like this harder. And more eyes on the wallet code means less bugs for Bails users and more people using codex32 with bitcoin core.
> 
> You will need a monitor, I don't have plans to write a Terminal User Interface for `bails-wallet` anytime soon.

OK, sounds great. Gives me time to brush up on python too.

**Comment by BenWestgate** [comment] 2023-09-09 16:37
The current `bails-wallet` file switches between bash and in-line python code frequently and that is one of the reasons it's large and harder than necessary to reason about.

**Comment by BenWestgate** [comment] 2023-09-09 16:45
Getting Hot..

```
error: Error parsing JSON: [{ "desc": "pkh(xprv9s21ZrQH143K3xy9DcYuprFDp99kGHMrRXfszZscqkTAwfUbcKP3dD5e5CaFhLMafApD4s4ki4fFrFvgisHYJjrkEQi3SUEZUnP4k4x7LSZ/44'/0'/0'/0/*)
error: Error parsing JSON: [{ "desc": "sh(wpkh(xprv9s21ZrQH143K3xy9DcYuprFDp99kGHMrRXfszZscqkTAwfUbcKP3dD5e5CaFhLMafApD4s4ki4fFrFvgisHYJjrkEQi3SUEZUnP4k4x7LSZ/49'/0'/0'/0/*))
error: Error parsing JSON: [{ "desc": "wpkh(xprv9s21ZrQH143K3xy9DcYuprFDp99kGHMrRXfszZscqkTAwfUbcKP3dD5e5CaFhLMafApD4s4ki4fFrFvgisHYJjrkEQi3SUEZUnP4k4x7LSZ/84'/0'/0'/0/*)
error: Error parsing JSON: [{ "desc": "tr(xprv9s21ZrQH143K3xy9DcYuprFDp99kGHMrRXfszZscqkTAwfUbcKP3dD5e5CaFhLMafApD4s4ki4fFrFvgisHYJjrkEQi3SUEZUnP4k4x7LSZ/86'/0'/0'/0/*)
error: Error parsing JSON: [{ "desc": "pkh(xprv9s21ZrQH143K3xy9DcYuprFDp99kGHMrRXfszZscqkTAwfUbcKP3dD5e5CaFhLMafApD4s4ki4fFrFvgisHYJjrkEQi3SUEZUnP4k4x7LSZ/44'/0'/0'/1/*)
error: Error parsing JSON: [{ "desc": "sh(wpkh(xprv9s21ZrQH143K3xy9DcYuprFDp99kGHMrRXfszZscqkTAwfUbcKP3dD5e5CaFhLMafApD4s4ki4fFrFvgisHYJjrkEQi3SUEZUnP4k4x7LSZ/49'/0'/0'/1/*))
error: Error parsing JSON: [{ "desc": "wpkh(xprv9s21ZrQH143K3xy9DcYuprFDp99kGHMrRXfszZscqkTAwfUbcKP3dD5e5CaFhLMafApD4s4ki4fFrFvgisHYJjrkEQi3SUEZUnP4k4x7LSZ/84'/0'/0'/1/*)
error: Error parsing JSON: [{ "desc": "tr(xprv9s21ZrQH143K3xy9DcYuprFDp99kGHMrRXfszZscqkTAwfUbcKP3dD5e5CaFhLMafApD4s4ki4fFrFvgisHYJjrkEQi3SUEZUnP4k4x7LSZ/86'/0'/0'/1/*)

```

It looks like the descriptor strings are missing closing quotes and braces! That'll make them fail to import for sure..

**Comment by extrapockets** [comment] 2023-09-09 16:49
If the scripting is solely in python, would that allow for the Codex32 utility to work on a non-linux OS? I think enough people use Linux that it's not necessary to have it work on Windows or MacOS right away, but 

> 

If the scripting is solely in python, would that allow for the Codex32 utility to work on a non-linux OS? Either way, I think enough people use Linux that it's not necessary to have it work on Windows or MacOS right away.

**Comment by BenWestgate** [comment] 2023-09-09 16:55
Yes, it means it would work on any OS with Python and Bitcoin Core.

**Comment by BenWestgate** [comment] 2023-09-09 17:36
I was missing quotes around the checksum's "#' in the descriptor import which made the rest of the line be interpreted as a comment. Run `git clone https://github.com/BenWestgate/Bails; */b` again and it should work just fine now.

**Closed by BenWestgate** 2023-09-09 17:36 UTC
Labels: bug, help wanted, priority: high, priority: medium
